/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegisterClientRouteImport } from './routes/register/client'
import { Route as RegisterProfessionalRouteImport } from './routes/register/professional'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterClientRoute = RegisterClientRouteImport.update({
  id: '/register/client',
  path: '/register/client',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterProfessionalRoute = RegisterProfessionalRouteImport.update({
  id: '/register/professional',
  path: '/register/professional',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/register/client': typeof RegisterClientRoute
  '/register/professional': typeof RegisterProfessionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/register/client': typeof RegisterClientRoute
  '/register/professional': typeof RegisterProfessionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/register/client': typeof RegisterClientRoute
  '/register/professional': typeof RegisterProfessionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/register/client' | '/register/professional'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/register/client' | '/register/professional'
  id:
    '__root__' | '/' | '/admin' | '/register/client' | '/register/professional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RegisterClientRoute: typeof RegisterClientRoute
  RegisterProfessionalRoute: typeof RegisterProfessionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/client': {
      id: '/register/client'
      path: '/register/client'
      fullPath: '/register/client'
      preLoaderRoute: typeof RegisterClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/professional': {
      id: '/register/professional'
      path: '/register/professional'
      fullPath: '/register/professional'
      preLoaderRoute: typeof RegisterProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RegisterClientRoute: RegisterClientRoute,
  RegisterProfessionalRoute: RegisterProfessionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
